# week 1: Basic Program

# 1.Basic Array Operations

In [1]:
import numpy as np
arr=np.array([1,2,3,4,5])
print("Array:",arr)
print("Add 5:",arr+5)
print("Multiply by 2:",arr*2)

Array: [1 2 3 4 5]
Add 5: [ 6  7  8  9 10]
Multiply by 2: [ 2  4  6  8 10]


# 2.Calculate Mean,Median and Standard Deviation


In [3]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print("Mean:",np.mean(arr))
print("Median:",np.median(arr))
print("Standard Deviation:",np.std(arr))

Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143


# 3.Reshaping Arrays

In [4]:
arr=np.arange(1,13)
reshaped_arr=arr.reshape(3,4)
print("Reshaped Array:\n",reshaped_arr)

Reshaped Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


# 4.Array Indexing

In [5]:
arr=np.array([10,20,30,40,50])
print("First Element:",arr[0])
print("Last Element:",arr[-1])
print("Slice(1 to 3):",arr[1:4])

First Element: 10
Last Element: 50
Slice(1 to 3): [20 30 40]


# 5.Array Concatenation

In [6]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
concatenated=np.concatenate((arr1,arr2))
print("concatenated Array:",concatenated)

concatenated Array: [1 2 3 4 5 6]


# 6.Boolean Indexing

In [8]:
arr=np.array([1,2,3,4,5])
filtered_arr=arr[arr>2]
print("filtered array(greater than 2):",filtered_arr)

filtered array(greater than 2): [3 4 5]


# 7.Dot Product

In [10]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
dot_product=np.dot(arr1,arr2)
print("Dot Product:",dot_product)

Dot Product: 32


# 8.Linear Algebra Operation

In [11]:
matrix=np.array([[1,2],[3,4]])
determinant=np.linalg.det(matrix)
inverse=np.linalg.inv(matrix)
print("Determinant:",determinant)
print("Inverse:\n",inverse)

Determinant: -2.0000000000000004
Inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]
